import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import styles from '../styles/Layout.module.scss'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>daily.Utility.[HUB]</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mainheader}>What do you Need?</h1>
        

       <Hero/>
        
      </main>

      
    </div>
  )
}


export default Home