import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Mcu( {mcu}) {

  console.log(mcu)
  return (
    <div className={styles.mcucontainer}>
      <Head>
        <title>Mcu</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mcuheader}>Marvel Cinematic Universe</h1>


        <div className={styles.mcu} >

        

        <div className={styles.card} >
        <h2>Upcoming</h2>

        <h1> Title: {mcu.title} </h1>
        <p> Release Date: {mcu.release_date} </p>
        <h3> {mcu.days_until} Days untill Release </h3>
        <img alt=""src={mcu.poster_url} />
        <p> {mcu.overview} </p>
  </div>

         
  <div className={styles.card} >
        <h2>One After</h2>

        <h1> Title: {mcu.following_production.title} </h1>
        <p> Release Date: {mcu.following_production.release_date} </p>
        <h3> {mcu.following_production.days_until} Days untill Release </h3>
<       img alt=""src={mcu.following_production.poster_url} />
        <h3> {mcu.following_production.overview} </h3>

</div>
</div>


      
        
      </main>

      
    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://www.whenisthenextmcufilm.com/api?date=2021-11-24")
  
  const mcu = await res.json()
  return {
    props: {
      mcu
    }
  }
}



export default Mcu