import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Memes( {meme} ) {
  console.log(meme)
  return (
    <div className={styles.memecontainer}>
      <Head>
        <title>Memes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mainheader}>Memes</h1>


        <ul className={styles.memelist}>
        {meme.posts.map((item,id)  => (
          <li key={id} className={styles.card} >
          <h3> Source: {item.subreddit_name_prefixed} </h3> 
          <img alt=""src={item.url} />
          </li>
        ))}
        </ul>

      
        
      </main>

      
    </div>
  )
}


export const getStaticProps = async () => {
  const res = await fetch("https://reddit3.p.rapidapi.com/subreddit?url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fmemes", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "reddit3.p.rapidapi.com",
      "x-rapidapi-key": "2ddc4c8cb4msh0c9e366b10869f2p1df196jsn9f56ebef905e"
    }
  })
  
  const meme = await res.json()
  return {
    props: {
      meme
    }
  }
}



export default Memes