import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Music( {music}) {

  console.log(music)

  return (
    <div className={styles.musiccontainer}>
      <Head>
        <title>Music</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mainheader}>Music</h1>


        <ul className={styles.musiclist}>
        {music.tracks.map((item,id)  => (
          <li key={id} className={styles.card} >
          <h2> Title: {item.title} </h2> 
          <h3> {item.subtitle} </h3>
          <img alt=""src={item.images.coverart} />
          <p> url{item.url} </p>
          </li>
        ))}
        </ul>
        

      
        
      </main>

      
    </div>
  )
}



export const getStaticProps = async () => {
  const res = await fetch("https://shazam.p.rapidapi.com/songs/list-recommendations?key=484129036&locale=en-US", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "shazam.p.rapidapi.com",
      "x-rapidapi-key": "2ddc4c8cb4msh0c9e366b10869f2p1df196jsn9f56ebef905e"
    }
  })
  
  const music = await res.json()
  return {
    props: {
      music
    }
  }
}



export default Music