import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Notes() {
  


  return (
    <div className={styles.container}>
      <Head>
        <title>Notes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.mainheader}>Notes</h1>


        <>
        <video 
      src="video/uc.mp4"  
      height="150px"
      width="200px"
      autoPlay
      muted={true}  
      loop={true}
      id="myVideo" />
        </>
  

      
        
      </main>

      
    </div>
  )
}


export default Notes